In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\Nisha_Classy\myenv\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\Nisha_Classy\myenv\Lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Nisha_Classy\myenv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Nisha_Classy\myenv\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\Users\Nisha_Classy\myenv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

## What is Pandas?
Pandas is a Python library used for working with data sets.

It has functions for analyzing, cleaning, exploring, and manipulating data.

The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

## Why Use Pandas?
Pandas allows us to analyze big data and make conclusions based on statistical theories.

Pandas can clean messy data sets, and make them readable and relevant.

Relevant data is very important in data science.

## Data sets in Pandas are usually multi-dimensional tables, called DataFrames.

Series is like a column, a DataFrame is the whole table

In [ ]:
import pandas as pd
# creating empty data frame
myvar = pd.DataFrame()
mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

# Load a DataFrame from a csv file

In [4]:
import pandas as pd
df=pd.read_csv("HR-Employee-Attrition.csv",header=0,index_col=0,quotechar='"',sep=',',na_values=["na","?",""," "],keep_default_na=False )

and other files ==>

In [ ]:
# # Also, among many other options...
# df = pd.read_html(url/html_string)
# df = pd.read_json(path/json_string)
# df = pd.read_sql(query, connection)
# df = pd.read_excel('filename.xlsx')
# df = pd.read_clipboard()  # e.g. from Excel copy

# Note: See the pandas documentation for arguments.

In [ ]:
#Fake Random Data (for Testing)
df = (pd.DataFrame(np.random.rand(100, 6),
                  columns=list('ABCDEF')) * 0.5).cumsum()

df['Group'] = [np.random.choice(list('abcd'))
               for _ in range(len(df))]

df['Date'] = pd.date_range('1/1/2017',
                           periods=len(df), freq='D')

# Hint: leave off the Group and/or Date cols if not needed

In [ ]:
# Saving a DataFrame
# Save to CSV
# df.to_csv('filename.csv', encoding='utf-8')

# Save to Excel
# writer = pd.ExcelWriter('filename.xlsx')
# df.to_excel(writer, 'Sheet1')
# writer.save()

## A DataFrame has 2 index

In [7]:
myvar.index

RangeIndex(start=0, stop=3, step=1)

In [8]:
myvar.columns

Index(['cars', 'passings'], dtype='str')

## Checking Pandas Version
The version string is stored under __version__ attribute.

In [9]:
import pandas as pd

print(pd.__version__)

3.0.1

## What is a Series?
A Pandas Series is like a column in a table.
A Series is an ordered , one-dimensional array holding data of any type.

In [10]:
num=[1,2,3,4,5]
num_series=pd.Series(num)
print(num_series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

# Create Labels
With the index argument, you can name your own labels.

In [11]:
#Create your own labels:

import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

x    1
y    7
z    2
dtype: int64

## Key/value objects as series

In [12]:
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64

In [1]:
import pandas as pd

calories = {
    "Fruits": ["apple", "banana", "orange","berries","pineapple","cherry","pomogranate","guava"],
    "Vitamins": ["Vitamin A", "Vitamin C", "Vitamin E", "Vitamin D","vitamin C","vitamin A","Vitamin A", "Vitamin C"],
    "Calories": [52, 89, 47, 50, 40, 60, 80, 30],
    "Fiber": [2.4, 2.6, 2.4, 1.8, 1.5, 3.0, 4.0, 2.2],
    "Sugar": [10.39, 12.23, 9.35, 8.0, 8.5, 13.0, 14.0, 5.0],
    "Protein": [0.26, 1.09, 0.94, 0.47, 0.5, 1.0, 1.5, 0.8],
    "Fat": [0.17, 0.33, 0.12, 0.15, 0.1, 0.2, 0.3, 0.1],
    "Carbohydrates": [13.81, 22.84, 11.75, 12.0, 10.0, 15.0, 20.0, 8.0],
    "Water": [85.56, 74.91, 86.75, 88.0, 90.0, 80.0, 70.0, 90.0],
    }

myvar = pd.DataFrame(calories)

print(myvar)

        Fruits   Vitamins  Calories  Fiber  Sugar  Protein   Fat  \
0        apple  Vitamin A        52    2.4  10.39     0.26  0.17
1       banana  Vitamin C        89    2.6  12.23     1.09  0.33
2       orange  Vitamin E        47    2.4   9.35     0.94  0.12
3      berries  Vitamin D        50    1.8   8.00     0.47  0.15
4    pineapple  vitamin C        40    1.5   8.50     0.50  0.10
5       cherry  vitamin A        60    3.0  13.00     1.00  0.20
6  pomogranate  Vitamin A        80    4.0  14.00     1.50  0.30
7        guava  Vitamin C        30    2.2   5.00     0.80  0.10

   Carbohydrates  Water
0          13.81  85.56
1          22.84  74.91
2          11.75  86.75
3          12.00  88.00
4          10.00  90.00
5          15.00  80.00
6          20.00  70.00
7           8.00  90.00

In [2]:
#Accssing the elements
print(myvar["Fruits"])

0          apple
1         banana
2         orange
3        berries
4      pineapple
5         cherry
6    pomogranate
7          guava
Name: Fruits, dtype: str

In [3]:
print(myvar.loc[0:3])

    Fruits   Vitamins  Calories  Fiber  Sugar  Protein   Fat  Carbohydrates  \
0    apple  Vitamin A        52    2.4  10.39     0.26  0.17          13.81
1   banana  Vitamin C        89    2.6  12.23     1.09  0.33          22.84
2   orange  Vitamin E        47    2.4   9.35     0.94  0.12          11.75
3  berries  Vitamin D        50    1.8   8.00     0.47  0.15          12.00

   Water
0  85.56
1  74.91
2  86.75
3  88.00

In [4]:
# # print(myvar.loc[0, "Fruits"]) #syntax :loc[row_index, column_name]
# print(myvar.loc[myvar["Calories"] > 50, "Fruits"])
myvar["Calories"] > 50

0     True
1     True
2    False
3    False
4    False
5     True
6     True
7    False
Name: Calories, dtype: bool

In [5]:
print(myvar.iloc[0:3, 0])

0     apple
1    banana
2    orange
Name: Fruits, dtype: str

In [6]:
print(myvar)

        Fruits   Vitamins  Calories  Fiber  Sugar  Protein   Fat  \
0        apple  Vitamin A        52    2.4  10.39     0.26  0.17
1       banana  Vitamin C        89    2.6  12.23     1.09  0.33
2       orange  Vitamin E        47    2.4   9.35     0.94  0.12
3      berries  Vitamin D        50    1.8   8.00     0.47  0.15
4    pineapple  vitamin C        40    1.5   8.50     0.50  0.10
5       cherry  vitamin A        60    3.0  13.00     1.00  0.20
6  pomogranate  Vitamin A        80    4.0  14.00     1.50  0.30
7        guava  Vitamin C        30    2.2   5.00     0.80  0.10

   Carbohydrates  Water
0          13.81  85.56
1          22.84  74.91
2          11.75  86.75
3          12.00  88.00
4          10.00  90.00
5          15.00  80.00
6          20.00  70.00
7           8.00  90.00

In [8]:
dropped_var=myvar.drop(myvar[myvar["Calories"] > 50].index)

In [18]:
print(myvar.iloc[0:3, 0]) #iloc uses integer-based indexing, so it selects the first three rows (0, 1, and 2) and the first column (0) of the DataFrame.
#iloc is

0     apple
1    banana
2    orange
Name: Fruits, dtype: str

In [ ]:
# groupby,sort_values,sort_index,astype,fillna,dropna,isna,isnull,sum,head,tail

In [89]:
print(myvar.head(1))

  Fruits   Vitamins  Calories  Fiber  Sugar  Protein   Fat  Carbohydrates  \
0  apple  Vitamin A        52    2.4  10.39     0.26  0.17          13.81

   Water
0  85.56

In [9]:
import numpy as np

myvar["Calories"].astype(int)

0    52
1    89
2    47
3    50
4    40
5    60
6    80
7    30
Name: Calories, dtype: int64

In [82]:
myvar.isna().sum()

Fruits           0
Vitamins         0
Calories         0
Fiber            0
Sugar            0
Protein          0
Fat              0
Carbohydrates    0
Water            0
dtype: int64

## Working with whole data frame

In [70]:
# Peek at the DataFrame (contents / structure)and basic info
df=pd.read_csv("HR-Employee-Attrition.csv",header=0,index_col=0,quotechar='"',sep=',',na_values=["na","?",""," "],keep_default_na=False)

print(df.info())       # print cols & data types


top_left_corner_df = df.iloc[:4, :4]

<class 'pandas.DataFrame'>
Index: 1470 entries, 41 to 34
Data columns (total 34 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Attrition                 1470 non-null   str
 1   BusinessTravel            1470 non-null   str
 2   DailyRate                 1470 non-null   int64
 3   Department                1470 non-null   str
 4   DistanceFromHome          1470 non-null   int64
 5   Education                 1470 non-null   int64
 6   EducationField            1470 non-null   str
 7   EmployeeCount             1470 non-null   int64
 8   EmployeeNumber            1470 non-null   int64
 9   EnvironmentSatisfaction   1470 non-null   int64
 10  Gender                    1470 non-null   str
 11  HourlyRate                1470 non-null   int64
 12  JobInvolvement            1470 non-null   int64
 13  JobLevel                  1470 non-null   int64
 14  JobRole                   1470 non-null   str
 15  JobSatisfaction           1470 non-null   int64
 16  MaritalStatus             1470 non-null   str
 17  MonthlyIncome             1470 non-null   int64
 18  MonthlyRate               1470 non-null   int64
 19  NumCompaniesWorked        1470 non-null   int64
 20  Over18                    1470 non-null   str
 21  OverTime                  1470 non-null   str
 22  PercentSalaryHike         1470 non-null   int64
 23  PerformanceRating         1470 non-null   int64
 24  RelationshipSatisfaction  1470 non-null   int64
 25  StandardHours             1470 non-null   int64
 26  StockOptionLevel          1470 non-null   int64
 27  TotalWorkingYears         1470 non-null   int64
 28  TrainingTimesLastYear     1470 non-null   int64
 29  WorkLifeBalance           1470 non-null   int64
 30  YearsAtCompany            1470 non-null   int64
 31  YearsInCurrentRole        1470 non-null   int64
 32  YearsSinceLastPromotion   1470 non-null   int64
 33  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(25), str(9)
memory usage: 402.0 KB
None

In [24]:
print(df.head(3))         # get first 3 rows

    Attrition     BusinessTravel  DailyRate              Department  \
Age
41        Yes      Travel_Rarely       1102                   Sales
49         No  Travel_Frequently        279  Research & Development
37        Yes      Travel_Rarely       1373  Research & Development

     DistanceFromHome  Education EducationField  EmployeeCount  \
Age
41                  1          2  Life Sciences              1
49                  8          1  Life Sciences              1
37                  2          2          Other              1

     EmployeeNumber  EnvironmentSatisfaction  ... RelationshipSatisfaction  \
Age                                           ...
41                1                        2  ...                        1
49                2                        3  ...                        4
37                4                        4  ...                        2

     StandardHours  StockOptionLevel  TotalWorkingYears TrainingTimesLastYear  \
Age
41              80                 0                  8                     0
49              80                 1                 10                     3
37              80                 0                  7                     3

     WorkLifeBalance YearsAtCompany  YearsInCurrentRole  \
Age
41                 1              6                   4
49                 3             10                   7
37                 3              0                   0

     YearsSinceLastPromotion  YearsWithCurrManager
Age
41                         0                     5
49                         1                     7
37                         0                     0

[3 rows x 34 columns]

In [25]:
print(df.tail(3))         # get last 3 rows

    Attrition     BusinessTravel  DailyRate              Department  \
Age
27         No      Travel_Rarely        155  Research & Development
49         No  Travel_Frequently       1023                   Sales
34         No      Travel_Rarely        628  Research & Development

     DistanceFromHome  Education EducationField  EmployeeCount  \
Age
27                  4          3  Life Sciences              1
49                  2          3        Medical              1
34                  8          3        Medical              1

     EmployeeNumber  EnvironmentSatisfaction  ... RelationshipSatisfaction  \
Age                                           ...
27             2064                        2  ...                        2
49             2065                        4  ...                        4
34             2068                        2  ...                        1

     StandardHours  StockOptionLevel  TotalWorkingYears TrainingTimesLastYear  \
Age
27              80                 1                  6                     0
49              80                 0                 17                     3
34              80                 0                  6                     3

     WorkLifeBalance YearsAtCompany  YearsInCurrentRole  \
Age
27                 3              6                   2
49                 2              9                   6
34                 4              4                   3

     YearsSinceLastPromotion  YearsWithCurrManager
Age
27                         0                     3
49                         0                     8
34                         1                     2

[3 rows x 34 columns]

In [26]:

print(df.describe())      # summary stats for cols

         DailyRate  DistanceFromHome    Education  EmployeeCount  \
count  1470.000000       1470.000000  1470.000000         1470.0
mean    802.485714          9.192517     2.912925            1.0
std     403.509100          8.106864     1.024165            0.0
min     102.000000          1.000000     1.000000            1.0
25%     465.000000          2.000000     2.000000            1.0
50%     802.000000          7.000000     3.000000            1.0
75%    1157.000000         14.000000     4.000000            1.0
max    1499.000000         29.000000     5.000000            1.0

       EmployeeNumber  EnvironmentSatisfaction   HourlyRate  JobInvolvement  \
count     1470.000000              1470.000000  1470.000000     1470.000000
mean      1024.865306                 2.721769    65.891156        2.729932
std        602.024335                 1.093082    20.329428        0.711561
min          1.000000                 1.000000    30.000000        1.000000
25%        491.250000                 2.000000    48.000000        2.000000
50%       1020.500000                 3.000000    66.000000        3.000000
75%       1555.750000                 4.000000    83.750000        3.000000
max       2068.000000                 4.000000   100.000000        4.000000

          JobLevel  JobSatisfaction  ...  RelationshipSatisfaction  \
count  1470.000000      1470.000000  ...               1470.000000
mean      2.063946         2.728571  ...                  2.712245
std       1.106940         1.102846  ...                  1.081209
min       1.000000         1.000000  ...                  1.000000
25%       1.000000         2.000000  ...                  2.000000
50%       2.000000         3.000000  ...                  3.000000
75%       3.000000         4.000000  ...                  4.000000
max       5.000000         4.000000  ...                  4.000000

       StandardHours  StockOptionLevel  TotalWorkingYears  \
count         1470.0       1470.000000        1470.000000
mean            80.0          0.793878          11.279592
std              0.0          0.852077           7.780782
min             80.0          0.000000           0.000000
25%             80.0          0.000000           6.000000
50%             80.0          1.000000          10.000000
75%             80.0          1.000000          15.000000
max             80.0          3.000000          40.000000

       TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
count            1470.000000      1470.000000     1470.000000
mean                2.799320         2.761224        7.008163
std                 1.289271         0.706476        6.126525
min                 0.000000         1.000000        0.000000
25%                 2.000000         2.000000        3.000000
50%                 3.000000         3.000000        5.000000
75%                 3.000000         3.000000        9.000000
max                 6.000000         4.000000       40.000000

       YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager
count         1470.000000              1470.000000           1470.000000
mean             4.229252                 2.187755              4.123129
std              3.623137                 3.222430              3.568136
min              0.000000                 0.000000              0.000000
25%              2.000000                 0.000000              2.000000
50%              3.000000                 1.000000              3.000000
75%              7.000000                 3.000000              7.000000
max             18.000000                15.000000             17.000000

[8 rows x 25 columns]

In [38]:
# DataFrame Non-Indexing Attributes

df_trans = df.T          # transpose rows and cols
print(df_trans.head(2))  # peek at the transposed DataFrame

Age                        41                 49             37  \
Attrition                 Yes                 No            Yes
BusinessTravel  Travel_Rarely  Travel_Frequently  Travel_Rarely

Age                            33             27                 32  \
Attrition                      No             No                 No
BusinessTravel  Travel_Frequently  Travel_Rarely  Travel_Frequently

Age                        59             30                 38  \
Attrition                  No             No                 No
BusinessTravel  Travel_Rarely  Travel_Rarely  Travel_Frequently

Age                        36  ...             29             50  \
Attrition                  No  ...             No            Yes
BusinessTravel  Travel_Rarely  ...  Travel_Rarely  Travel_Rarely

Age                        39          31             26                 36  \
Attrition                  No          No             No                 No
BusinessTravel  Travel_Rarely  Non-Travel  Travel_Rarely  Travel_Frequently

Age                        39             27                 49             34
Attrition                  No             No                 No             No
BusinessTravel  Travel_Rarely  Travel_Rarely  Travel_Frequently  Travel_Rarely

[2 rows x 1470 columns]

In [39]:
df.axes        # list of row & col indexes

[Index([41, 49, 37, 33, 27, 32, 59, 30, 38, 36,
        ...
        29, 50, 39, 31, 26, 36, 39, 27, 49, 34],
       dtype='int64', name='Age', length=1470),
 Index(['Attrition', 'BusinessTravel', 'DailyRate', 'Department',
        'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
        'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
        'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
        'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
        'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
        'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
        'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
        'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
        'YearsWithCurrManager'],
       dtype='str')]

In [40]:
r,c=df.axes     # from above
print(r)     # row index
print(c)     # col index

Index([41, 49, 37, 33, 27, 32, 59, 30, 38, 36,
       ...
       29, 50, 39, 31, 26, 36, 39, 27, 49, 34],
      dtype='int64', name='Age', length=1470)
Index(['Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='str')

In [41]:
df.dtypes      # Series: column data types

Attrition                     str
BusinessTravel                str
DailyRate                   int64
Department                    str
DistanceFromHome            int64
Education                   int64
EducationField                str
EmployeeCount               int64
EmployeeNumber              int64
EnvironmentSatisfaction     int64
Gender                        str
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobRole                       str
JobSatisfaction             int64
MaritalStatus                 str
MonthlyIncome               int64
MonthlyRate                 int64
NumCompaniesWorked          int64
Over18                        str
OverTime                      str
PercentSalaryHike           int64
PerformanceRating           int64
RelationshipSatisfaction    int64
StandardHours               int64
StockOptionLevel            int64
TotalWorkingYears           int64
TrainingTimesLastYear       int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
dtype: object

In [42]:
df.empty       # True for empty DataFrame

False

In [43]:
df.ndim        # number of axes (usually 2)

2

In [44]:
df.shape       # (row_count, column_count)

(1470, 34)

In [45]:
df.size        # total elements (rows * cols)

49980

In [46]:
df.values # numpy matrix of df values (no row/col labels)

array([['Yes', 'Travel_Rarely', 1102, ..., 4, 0, 5],
       ['No', 'Travel_Frequently', 279, ..., 7, 1, 7],
       ['Yes', 'Travel_Rarely', 1373, ..., 0, 0, 0],
       ...,
       ['No', 'Travel_Rarely', 155, ..., 2, 0, 3],
       ['No', 'Travel_Frequently', 1023, ..., 6, 0, 8],
       ['No', 'Travel_Rarely', 628, ..., 3, 1, 2]],
      shape=(1470, 34), dtype=object)

In [10]:
# # DataFrame Iteration Methods
# # Iterate over columns
# for col_name, series in df.items():
#     print(col_name)
#     print(series.head())

# # Iterate over rows
# for index, row in df.iterrows():
#     print(index)
#     print(row)

In [50]:
# DataFrame Utility Methods
df_copy = df.copy()                          # copy a DataFrame

In [5]:
df.sort_values(by='RelationshipSatisfaction')           # sort by one column
#  df.sort_values(by=[col1, col2])    # sort by multiple cols

,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
Age,,,,,,,,,,,,,,,,,,,,,
46,Yes,Travel_Rarely,377,Sales,9,3,Marketing,1,1457,1,...,1,80,1,28,1,4,7,7,4,3
31,Yes,Travel_Frequently,1445,Research & Development,1,5,Life Sciences,1,1459,3,...,1,80,0,10,2,3,10,8,4,7
37,No,Travel_Rarely,1462,Research & Development,11,3,Medical,1,1411,1,...,1,80,0,8,6,3,3,2,0,2
29,No,Travel_Rarely,332,Human Resources,17,3,Other,1,1419,2,...,1,80,0,10,3,2,10,9,0,9
49,Yes,Travel_Frequently,1475,Research & Development,28,2,Life Sciences,1,1420,1,...,1,80,0,20,2,3,4,3,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44,No,Travel_Rarely,477,Research & Development,7,4,Medical,1,36,1,...,4,80,1,24,4,3,22,6,5,17
42,No,Travel_Rarely,691,Sales,8,4,Marketing,1,35,3,...,4,80,1,10,2,3,9,7,4,2
49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,4,...,4,80,0,17,3,2,9,6,0,8
27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,...,4,80,1,6,3,3,2,2,2,2
49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,...,4,80,1,10,3,3,10,7,1,7

In [6]:
df.sort_values(by='DistanceFromHome',axis=0)     # sort columns

,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
Age,,,,,,,,,,,,,,,,,,,,,
41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,...,1,80,0,8,0,1,6,4,0,5
35,No,Travel_Rarely,287,Research & Development,1,4,Life Sciences,1,2052,3,...,4,80,1,4,5,3,4,3,1,1
50,Yes,Travel_Frequently,878,Sales,1,4,Life Sciences,1,2044,2,...,4,80,2,12,3,3,6,3,0,1
28,Yes,Travel_Frequently,1009,Research & Development,1,3,Medical,1,1111,1,...,1,80,2,1,2,3,1,0,0,0
59,No,Travel_Rarely,1089,Sales,1,2,Technical Degree,1,1048,2,...,3,80,1,14,1,1,6,4,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,No,Travel_Rarely,210,Sales,29,3,Marketing,1,568,1,...,3,80,1,32,3,2,1,0,0,0
30,No,Travel_Rarely,1288,Sales,29,4,Technical Degree,1,1568,3,...,2,80,1,9,3,3,4,2,1,3
45,No,Travel_Rarely,1448,Research & Development,29,3,Technical Degree,1,1465,2,...,4,80,2,10,4,4,3,1,1,2
28,No,Travel_Rarely,1083,Research & Development,29,1,Life Sciences,1,1514,3,...,2,80,2,8,2,2,8,6,1,7
52,No,Non-Travel,585,Sales,29,4,Life Sciences,1,2019,1,...,2,80,2,16,3,2,9,8,0,0

In [72]:
df.sort_index()                    # sort index

,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
Age,,,,,,,,,,,,,,,,,,,,,
18,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,1,614,2,...,4,80,0,0,3,3,0,0,0,0
18,Yes,Non-Travel,247,Research & Development,8,1,Medical,1,1156,3,...,4,80,0,0,0,3,0,0,0,0
18,Yes,Travel_Frequently,544,Sales,3,2,Medical,1,1624,2,...,3,80,0,0,2,4,0,0,0,0
18,No,Non-Travel,1431,Research & Development,14,3,Medical,1,1839,2,...,3,80,0,0,4,1,0,0,0,0
18,No,Travel_Rarely,812,Sales,10,3,Medical,1,411,4,...,1,80,0,0,2,3,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,No,Travel_Frequently,1499,Sales,28,3,Marketing,1,573,3,...,4,80,0,22,5,4,18,13,13,11
60,No,Travel_Rarely,422,Research & Development,7,3,Life Sciences,1,549,1,...,4,80,0,33,5,1,29,8,11,10
60,No,Travel_Rarely,1179,Sales,16,4,Marketing,1,732,1,...,4,80,0,10,1,3,2,2,2,2
60,No,Travel_Rarely,696,Sales,7,4,Marketing,1,1233,2,...,2,80,1,12,3,3,11,7,1,9
60,No,Travel_Rarely,370,Research & Development,1,4,Medical,1,1697,3,...,3,80,1,19,2,4,1,0,0,0

In [73]:
df["PerformanceRating"].astype('float64')                   # type conversion

Age
41    3.0
49    4.0
37    3.0
33    3.0
27    3.0
     ...
36    3.0
39    3.0
27    4.0
49    3.0
34    3.0
Name: PerformanceRating, Length: 1470, dtype: float64

In [71]:
df.dtypes

Attrition                     str
BusinessTravel                str
DailyRate                   int64
Department                    str
DistanceFromHome            int64
Education                   int64
EducationField                str
EmployeeCount               int64
EmployeeNumber              int64
EnvironmentSatisfaction     int64
Gender                        str
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobRole                       str
JobSatisfaction             int64
MaritalStatus                 str
MonthlyIncome               int64
MonthlyRate                 int64
NumCompaniesWorked          int64
Over18                        str
OverTime                      str
PercentSalaryHike           int64
PerformanceRating           int64
RelationshipSatisfaction    int64
StandardHours               int64
StockOptionLevel            int64
TotalWorkingYears           int64
TrainingTimesLastYear       int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
dtype: object

In [99]:
print(df[df["Department"] == "Sales"].groupby("Department"))

<pandas.api.typing.DataFrameGroupBy object at 0x0000014815C8EE50>

In [96]:
df["Department"]

Age
41                     Sales
49    Research & Development
37    Research & Development
33    Research & Development
27    Research & Development
               ...
36    Research & Development
39    Research & Development
27    Research & Development
49                     Sales
34    Research & Development
Name: Department, Length: 1470, dtype: str

In [1]:
import pandas as pd

employees = pd.DataFrame({
    'emp_id': [101, 102, 103, 104],
    'name': ['Nisha', 'Rahul', 'Amit', 'Sneha'],
    'dept_id': [1, 2, 1, 3]
})

print(employees)

   emp_id   name  dept_id
0     101  Nisha        1
1     102  Rahul        2
2     103   Amit        1
3     104  Sneha        3

In [2]:
departments = pd.DataFrame({
    'dept_id': [1, 2, 4],
    'dept_name': ['HR', 'IT', 'Finance']
})

print(departments)

   dept_id dept_name
0        1        HR
1        2        IT
2        4   Finance

In [4]:
inner_join=pd.merge(employees,departments, on='dept_id',how='inner')
print(inner_join)

   emp_id   name  dept_id dept_name
0     101  Nisha        1        HR
1     102  Rahul        2        IT
2     103   Amit        1        HR

In [5]:
outer_join=pd.merge(employees,departments,on='dept_id',how='outer')
print(outer_join)

   emp_id   name  dept_id dept_name
0   101.0  Nisha        1        HR
1   103.0   Amit        1        HR
2   102.0  Rahul        2        IT
3   104.0  Sneha        3       NaN
4     NaN    NaN        4   Finance

In [8]:
outer_join=pd.merge(employees,departments,on='dept_id',how='outer')
print(outer_join)

   emp_id   name  dept_id dept_name
0   101.0  Nisha        1        HR
1   103.0   Amit        1        HR
2   102.0  Rahul        2        IT
3   104.0  Sneha        3       NaN
4     NaN    NaN        4   Finance

In [9]:
right_join=pd.merge(employees,departments,on='dept_id',how='right')
print(right_join)

   emp_id   name  dept_id dept_name
0   101.0  Nisha        1        HR
1   103.0   Amit        1        HR
2   102.0  Rahul        2        IT
3     NaN    NaN        4   Finance

In [10]:
outer_join=pd.merge(employees,departments, on='dept_id',how='outer')
print(outer_join)

   emp_id   name  dept_id dept_name
0   101.0  Nisha        1        HR
1   103.0   Amit        1        HR
2   102.0  Rahul        2        IT
3   104.0  Sneha        3       NaN
4     NaN    NaN        4   Finance

In [13]:
joinn=pd.merge(employees,departments,left_on='dept_id',right_on='dept_id')
print(joinn)

   emp_id   name  dept_id dept_name
0     101  Nisha        1        HR
1     102  Rahul        2        IT
2     103   Amit        1        HR

In [14]:
# Step 1: Identify the Target Column 

# Ask: What am I trying to predict?

# If predicting a number → Regression

# If predicting a category/label → Classification

# Core Rule (Golden Rule)
# Target Type	Problem Type
# Continuous values (price, salary, temperature)	Regression
# # Discrete labels (yes/no, fraud/not fraud)	Classification

In [8]:
# maths in pandas

In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, -2, 3],
    'B': [4, 5, -6]
})

print(df)

   A  B
0  1  4
1 -2  5
2  3 -6

In [3]:
df.abs()

   A  B
0  1  4
1  2  5
2  3  6

In [4]:
df.add(2)

   A  B
0  3  6
1  0  7
2  5 -4

In [5]:
df.count()

A    3
B    3
dtype: int64

In [6]:
df.cummax()

   A  B
0  1  4
1  1  5
2  3  5

In [7]:
df.cummin()

   A  B
0  1  4
1 -2  4
2 -2 -6

In [8]:
# CUMSUM
df.cumsum()

   A  B
0  1  4
1 -1  9
2  2  3

In [9]:
# dot() → matrix multiplication
df.dot(df.T)

    0   1   2
0  17  18 -21
1  18  29 -36
2 -21 -36  45

In [10]:
df.diff()

     A     B
0  NaN   NaN
1 -3.0   1.0
2  5.0 -11.0

In [11]:
df.div(2)

     A    B
0  0.5  2.0
1 -1.0  2.5
2  1.5 -3.0

In [ ]:
#maximum value in each column
df.max()

A    3
B    5
dtype: int64

In [ ]:
#minimum value in each column
df.min()

A   -2
B   -6
dtype: int64

In [ ]:
#mean() → mean value of each column
df.mean()

A    0.666667
B    1.000000
dtype: float64

In [ ]:
#mode() → most frequent value in each column
df.mode()

   A  B
0 -2 -6
1  1  4
2  3  5

In [ ]:
# median() → median value of each column
df.median()

A    1.0
B    4.0
dtype: float64

In [ ]:
# multiply() → element-wise multiplication
df.mul(3)

   A   B
0  3  12
1 -6  15
2  9 -18

In [ ]:
#Using conditional logic to replace values in a DataFrame
df=df.where(df > 0, other=np.nan)
print(df)

     A    B
0  1.0  4.0
1  NaN  5.0
2  3.0  NaN

In [20]:
df=df.fillna(df.median())
print(df)

     A    B
0  1.0  4.0
1  2.0  5.0
2  3.0  4.5

In [21]:
df.div(3)

          A         B
0  0.333333  1.333333
1  0.666667  1.666667
2  1.000000  1.500000

In [12]:
emp=pd.read_csv("HR-Employee-Attrition.csv",header=0,index_col=0,quotechar='"',sep=',',na_values=["na","?",""," "],keep_default_na=False)

print(emp.info())

<class 'pandas.DataFrame'>
Index: 1470 entries, 41 to 34
Data columns (total 34 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Attrition                 1470 non-null   str
 1   BusinessTravel            1470 non-null   str
 2   DailyRate                 1470 non-null   int64
 3   Department                1470 non-null   str
 4   DistanceFromHome          1470 non-null   int64
 5   Education                 1470 non-null   int64
 6   EducationField            1470 non-null   str
 7   EmployeeCount             1470 non-null   int64
 8   EmployeeNumber            1470 non-null   int64
 9   EnvironmentSatisfaction   1470 non-null   int64
 10  Gender                    1470 non-null   str
 11  HourlyRate                1470 non-null   int64
 12  JobInvolvement            1470 non-null   int64
 13  JobLevel                  1470 non-null   int64
 14  JobRole                   1470 non-null   str
 15  JobSatisfaction           1470 non-null   int64
 16  MaritalStatus             1470 non-null   str
 17  MonthlyIncome             1470 non-null   int64
 18  MonthlyRate               1470 non-null   int64
 19  NumCompaniesWorked        1470 non-null   int64
 20  Over18                    1470 non-null   str
 21  OverTime                  1470 non-null   str
 22  PercentSalaryHike         1470 non-null   int64
 23  PerformanceRating         1470 non-null   int64
 24  RelationshipSatisfaction  1470 non-null   int64
 25  StandardHours             1470 non-null   int64
 26  StockOptionLevel          1470 non-null   int64
 27  TotalWorkingYears         1470 non-null   int64
 28  TrainingTimesLastYear     1470 non-null   int64
 29  WorkLifeBalance           1470 non-null   int64
 30  YearsAtCompany            1470 non-null   int64
 31  YearsInCurrentRole        1470 non-null   int64
 32  YearsSinceLastPromotion   1470 non-null   int64
 33  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(25), str(9)
memory usage: 402.0 KB
None

In [13]:
emp["DailyRate"]=emp['DailyRate'].astype(float)

In [14]:
print(emp.info())

<class 'pandas.DataFrame'>
Index: 1470 entries, 41 to 34
Data columns (total 34 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Attrition                 1470 non-null   str
 1   BusinessTravel            1470 non-null   str
 2   DailyRate                 1470 non-null   float64
 3   Department                1470 non-null   str
 4   DistanceFromHome          1470 non-null   int64
 5   Education                 1470 non-null   int64
 6   EducationField            1470 non-null   str
 7   EmployeeCount             1470 non-null   int64
 8   EmployeeNumber            1470 non-null   int64
 9   EnvironmentSatisfaction   1470 non-null   int64
 10  Gender                    1470 non-null   str
 11  HourlyRate                1470 non-null   int64
 12  JobInvolvement            1470 non-null   int64
 13  JobLevel                  1470 non-null   int64
 14  JobRole                   1470 non-null   str
 15  JobSatisfaction           1470 non-null   int64
 16  MaritalStatus             1470 non-null   str
 17  MonthlyIncome             1470 non-null   int64
 18  MonthlyRate               1470 non-null   int64
 19  NumCompaniesWorked        1470 non-null   int64
 20  Over18                    1470 non-null   str
 21  OverTime                  1470 non-null   str
 22  PercentSalaryHike         1470 non-null   int64
 23  PerformanceRating         1470 non-null   int64
 24  RelationshipSatisfaction  1470 non-null   int64
 25  StandardHours             1470 non-null   int64
 26  StockOptionLevel          1470 non-null   int64
 27  TotalWorkingYears         1470 non-null   int64
 28  TrainingTimesLastYear     1470 non-null   int64
 29  WorkLifeBalance           1470 non-null   int64
 30  YearsAtCompany            1470 non-null   int64
 31  YearsInCurrentRole        1470 non-null   int64
 32  YearsSinceLastPromotion   1470 non-null   int64
 33  YearsWithCurrManager      1470 non-null   int64
dtypes: float64(1), int64(24), str(9)
memory usage: 402.0 KB
None

In [15]:
emp.filter(items=['Department','EducationField','JobRole','MaritalStatus','MonthlyIncome','NumCompaniesWorked','OverTime'])

,Department,EducationField,JobRole,MaritalStatus,MonthlyIncome,NumCompaniesWorked,OverTime
Age,,,,,,,
41,Sales,Life Sciences,Sales Executive,Single,5993,8,Yes
49,Research & Development,Life Sciences,Research Scientist,Married,5130,1,No
37,Research & Development,Other,Laboratory Technician,Single,2090,6,Yes
33,Research & Development,Life Sciences,Research Scientist,Married,2909,1,Yes
27,Research & Development,Medical,Laboratory Technician,Married,3468,9,No
...,...,...,...,...,...,...,...
36,Research & Development,Medical,Laboratory Technician,Married,2571,4,No
39,Research & Development,Medical,Healthcare Representative,Married,9991,4,No
27,Research & Development,Life Sciences,Manufacturing Director,Married,6142,1,Yes
49,Sales,Medical,Sales Executive,Married,5390,2,No
34,Research & Development,Medical,Laboratory Technician,Married,4404,2,No

In [16]:
emp.head(1)

,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
Age,,,,,,,,,,,,,,,,,,,,,
41,Yes,Travel_Rarely,1102.0,Sales,1,2,Life Sciences,1,1,2,...,1,80,0,8,0,1,6,4,0,5

In [17]:
emp.filter(items=['Department','EducationField','JobRole','MonthlyIncome'],axis=1)

,Department,EducationField,JobRole,MonthlyIncome
Age,,,,
41,Sales,Life Sciences,Sales Executive,5993
49,Research & Development,Life Sciences,Research Scientist,5130
37,Research & Development,Other,Laboratory Technician,2090
33,Research & Development,Life Sciences,Research Scientist,2909
27,Research & Development,Medical,Laboratory Technician,3468
...,...,...,...,...
36,Research & Development,Medical,Laboratory Technician,2571
39,Research & Development,Medical,Healthcare Representative,9991
27,Research & Development,Life Sciences,Manufacturing Director,6142
49,Sales,Medical,Sales Executive,5390
34,Research & Development,Medical,Laboratory Technician,4404

In [18]:
emp.filter(like='Edu')

     Education EducationField
Age
41           2  Life Sciences
49           1  Life Sciences
37           2          Other
33           4  Life Sciences
27           1        Medical
..         ...            ...
36           2        Medical
39           1        Medical
27           3  Life Sciences
49           3        Medical
34           3        Medical

[1470 rows x 2 columns]

In [19]:
print(emp.filter(regex='Edu'))

     Education EducationField
Age
41           2  Life Sciences
49           1  Life Sciences
37           2          Other
33           4  Life Sciences
27           1        Medical
..         ...            ...
36           2        Medical
39           1        Medical
27           3  Life Sciences
49           3        Medical
34           3        Medical

[1470 rows x 2 columns]

In [20]:
print(emp.select_dtypes(include=[np.number]))

     DailyRate  DistanceFromHome  Education  EmployeeCount  EmployeeNumber  \
Age
41      1102.0                 1          2              1               1
49       279.0                 8          1              1               2
37      1373.0                 2          2              1               4
33      1392.0                 3          4              1               5
27       591.0                 2          1              1               7
..         ...               ...        ...            ...             ...
36       884.0                23          2              1            2061
39       613.0                 6          1              1            2062
27       155.0                 4          3              1            2064
49      1023.0                 2          3              1            2065
34       628.0                 8          3              1            2068

     EnvironmentSatisfaction  HourlyRate  JobInvolvement  JobLevel  \
Age
41                         2          94               3         2
49                         3          61               2         2
37                         4          92               2         1
33                         4          56               3         1
27                         1          40               3         1
..                       ...         ...             ...       ...
36                         3          41               4         2
39                         4          42               2         3
27                         2          87               4         2
49                         4          63               2         2
34                         2          82               4         2

     JobSatisfaction  ...  RelationshipSatisfaction  StandardHours  \
Age                   ...
41                 4  ...                         1             80
49                 2  ...                         4             80
37                 3  ...                         2             80
33                 3  ...                         3             80
27                 2  ...                         4             80
..               ...  ...                       ...            ...
36                 4  ...                         3             80
39                 1  ...                         1             80
27                 2  ...                         2             80
49                 2  ...                         4             80
34                 3  ...                         1             80

     StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
Age
41                  0                  8                      0
49                  1                 10                      3
37                  0                  7                      3
33                  0                  8                      3
27                  1                  6                      3
..                ...                ...                    ...
36                  1                 17                      3
39                  1                  9                      5
27                  1                  6                      0
49                  0                 17                      3
34                  0                  6                      3

     WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
Age
41                 1               6                   4
49                 3              10                   7
37                 3               0                   0
33                 3               8                   7
27                 3               2                   2
..               ...             ...                 ...
36                 3               5                   2
39                 3               7                   7
27                 3               6                   2
49                 2               9                   6
34                 4               4                   3

     YearsSinceLastPromotion  YearsWithCurrManager
Age
41                         0                     5
49                         1                     7
37                         0                     0
33                         3                     0
27                         2                     2
..                       ...                   ...
36                         0                     3
39                         1                     7
27                         0                     3
49                         0                     8
34                         1                     2

[1470 rows x 25 columns]

## Get column index and labels

In [26]:
emp.columns

Index(['Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='str')

In [ ]:
emp.columns[0] #first column name

'Attrition'

In [ ]:
emp_list=emp.columns.tolist() #list of column names

In [22]:
print(emp_list)

['Attrition', 'BusinessTravel', 'DailyRate', 'Department', 'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

In [24]:
emp_values=emp.columns.values
print(emp_values)

<StringArray>
[               'Attrition',           'BusinessTravel',
                'DailyRate',               'Department',
         'DistanceFromHome',                'Education',
           'EducationField',            'EmployeeCount',
           'EmployeeNumber',  'EnvironmentSatisfaction',
                   'Gender',               'HourlyRate',
           'JobInvolvement',                 'JobLevel',
                  'JobRole',          'JobSatisfaction',
            'MaritalStatus',            'MonthlyIncome',
              'MonthlyRate',       'NumCompaniesWorked',
                   'Over18',                 'OverTime',
        'PercentSalaryHike',        'PerformanceRating',
 'RelationshipSatisfaction',            'StandardHours',
         'StockOptionLevel',        'TotalWorkingYears',
    'TrainingTimesLastYear',          'WorkLifeBalance',
           'YearsAtCompany',       'YearsInCurrentRole',
  'YearsSinceLastPromotion',     'YearsWithCurrManager']
Length: 34, dtype: str

In [25]:
emp_values=emp.columns.values.tolist()
print(emp_values)

['Attrition', 'BusinessTravel', 'DailyRate', 'Department', 'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

## Change column labels

In [28]:
emp_columns=emp.rename(columns={'Department':'Dept','EducationField':'EduField','JobRole':'Job','MaritalStatus':'Marital','MonthlyIncome':'Income','NumCompaniesWorked':'NumComp','OverTime':'OT'})
print(emp_columns.columns)

Index(['Attrition', 'BusinessTravel', 'DailyRate', 'Dept', 'DistanceFromHome',
       'Education', 'EduField', 'EmployeeCount', 'EmployeeNumber',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'Job', 'JobSatisfaction', 'Marital', 'Income',
       'MonthlyRate', 'NumComp', 'Over18', 'OT', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='str')

## Selecting columns

In [ ]:
emp[['Attrition','Department']] # selecting specific columns

    Attrition              Department
Age
41        Yes                   Sales
49         No  Research & Development
37        Yes  Research & Development
33         No  Research & Development
27         No  Research & Development
..        ...                     ...
36         No  Research & Development
39         No  Research & Development
27         No  Research & Development
49         No                   Sales
34         No  Research & Development

[1470 rows x 2 columns]

In [35]:
emp[['Attrition','Department','EducationField']] #changing order of columns

    Attrition              Department EducationField
Age
41        Yes                   Sales  Life Sciences
49         No  Research & Development  Life Sciences
37        Yes  Research & Development          Other
33         No  Research & Development  Life Sciences
27         No  Research & Development        Medical
..        ...                     ...            ...
36         No  Research & Development        Medical
39         No  Research & Development        Medical
27         No  Research & Development  Life Sciences
49         No                   Sales        Medical
34         No  Research & Development        Medical

[1470 rows x 3 columns]

In [37]:
emp.columns[0] # access by column index

'Attrition'

In [38]:
emp.pop('EducationField') # get and drop off

Age
41    Life Sciences
49    Life Sciences
37            Other
33    Life Sciences
27          Medical
          ...
36          Medical
39          Medical
27    Life Sciences
49          Medical
34          Medical
Name: EducationField, Length: 1470, dtype: str

## Selecting columns with python attributes

In [43]:
emp.Department # same as emp['Department']

Age
41                     Sales
49    Research & Development
37    Research & Development
33    Research & Development
27    Research & Development
               ...
36    Research & Development
39    Research & Development
27    Research & Development
49                     Sales
34    Research & Development
Name: Department, Length: 1470, dtype: str

## Adding new columns to a dataframe

In [ ]:
emp['new_column'] = range(len(emp))
print(emp['new_column'])

Age
41       0
49       1
37       2
33       3
27       4
      ...
36    1465
39    1466
27    1467
49    1468
34    1469
Name: new_column, Length: 1470, dtype: int64

In [48]:
emp=emp.rename(columns={'new_column':'range'})

In [1]:
# 3d array
import numpy as np
dim_3=np.array([[[1,2],[3,4]], [[5,6],[7,8]]])

In [2]:
# hstack() → Horizontal Stack
#  Joins arrays side by side (columns increase)

a = np.array([1, 2])
b = np.array([3, 4])

np.hstack((a, b))

array([1, 2, 3, 4])

In [ ]:
# 2. vstack() → Vertical Stack

# Joins arrays top to bottom (rows increase)

np.vstack((a, b))

In [ ]:
# 3. dstack() → Depth Stack

# Joins arrays along 3rd dimension

a = np.array([[1,2]])
b = np.array([[3,4]])

np.dstack((a, b))

In [9]:
#INSERTION
#1-D ARRAY

one_d = np.array([1, 2, 3])

np.insert(one_d, 1, 99)

array([ 1, 99,  2,  3])

In [10]:
#INSERTION
#2-D ARRAY

two_d = np.array([[1, 2], [3, 4]])

np.insert(two_d, 1, 99, axis=1)

array([[ 1, 99,  2],
       [ 3, 99,  4]])

In [8]:
arr=np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
new_col = [[[9],[9]]]
np.insert(arr, 1, new_col, axis=1)

array([[[1, 2],
        [9, 9],
        [3, 4]],

       [[5, 6],
        [9, 9],
        [7, 8]]])

In [ ]:
# Axis	Meaning
# axis=0	depth (add new block)
# axis=1	rows
# axis=2	columns

In [14]:
arr = np.array([[1,2],[3,4]])

np.insert(arr, 1, [9,9], axis=1)   # row insert

array([[1, 9, 2],
       [3, 9, 4]])

In [5]:
# Add a mismatched column with an extended index

df = pd.DataFrame([1, 2, 3], index=[1, 2, 3])
s = pd.Series([2, 3, 4], index=[2, 3, 4])
df = df.reindex(df.index.union(s.index))
df['s'] = s  # with NaNs where no data

In [6]:
import pandas as pd
print(s)
print(df)

2    2
3    3
4    4
dtype: int64
     0    s
1  1.0  NaN
2  2.0  2.0
3  3.0  3.0
4  NaN  4.0

In [1]:
# # Dropping (deleting) columns (mostly by label)

# df = df.drop(col1, axis=1)
# df = df.drop([col1, col2], axis=1)
# del df[col]      # even classic Python works
# df = df.drop(df.columns[0], axis=1)    # first column
# df = df.drop(df.columns[-1], axis=1)   # last column

In [ ]:
# Swap column contents
df[['B', 'A']] = df[['A', 'B']]

In [ ]:
# Vectorised arithmetic on columns
df['proportion'] = df['count'] / df['total']
df['percent'] = df['proportion'] * 100.0

In [3]:
# Apply numpy mathematical functions to columns
import pandas as pd     
import numpy as np
df_p=pd.DataFrame({"attendance": [1, 2, 3, 4, 5]})
df_p['log_data'] = np.log(df_p['attendance'])
print(df_p)

   attendance  log_data
0           1  0.000000
1           2  0.693147
2           3  1.098612
3           4  1.386294
4           5  1.609438

In [9]:
# Set column values set based on criteria
# df[b] = df[a].where(df[a] > 0, other=0)
# df[d] = df[a].where(df[a] <= 0, other=df[c])
import pandas as pd

df = pd.DataFrame({
    'a': [5, -3, 7, -2],
    'c': [10, 20, 30, 40]
})

print(df)

   a   c
0  5  10
1 -3  20
2  7  30
3 -2  40

In [10]:
#Replace negative values with 0
df['b'] = df['a'].where(df['a'] > 0, other=0)

In [11]:
# Replace positive values with values from another column
df['d'] = df['a'].where(df['a'] <= 0, other=df['c'])

In [12]:
print(df)

   a   c  b   d
0  5  10  5  10
1 -3  20  0  -3
2  7  30  7  30
3 -2  40  0  -2

In [13]:
df=df.drop(columns=['a', 'd'])
print(df)

    c  b
0  10  5
1  20  0
2  30  7
3  40  0

In [ ]:
# Data type conversions
s = df[col].astype('float')
s = df[col].astype('int')
s = pd.to_numeric(df[col])
s = df[col].astype('str')
s = df[col].values      # numpy array
l = df[col].tolist()    # python list
#index lost on conversion from Series to array or list

In [37]:
import pandas as pd

df = pd.DataFrame({
    'marks': [80.899, 90, None, 70, 60],
    'age': [20, 21, 22, 20, 23]
})

print(df)

    marks  age
0  80.899   20
1  90.000   21
2     NaN   22
3  70.000   20
4  60.000   23

In [38]:
# Apply ALL column-wide methods on marks
# 1. dtype (data type)
df['marks'].dtype

dtype('float64')

In [39]:
# 2. size (total elements including NaN)
df['marks'].size

5

In [40]:
# 3. count (non-NaN values)
df['marks'].count()

4

In [41]:
# 5. product
df['marks'].prod()

30579822.0

In [42]:
# 6. minimum value
df['marks'].min()

60.0

In [43]:
# 7. maximum value
df['marks'].max()

90.0

In [44]:
# 8. mean (average)
df['marks'].mean()

75.22475

In [45]:
# covariance with another column
df['marks'].cov(df['age'])

-10.299666666666667

In [46]:
# 10. describe (summary stats)
df['marks'].describe()

count     4.000000
mean     75.224750
std      13.033241
min      60.000000
25%      67.500000
50%      75.449500
75%      83.174250
max      90.000000
Name: marks, dtype: float64

In [47]:
# 11. value_counts (frequency of values)
df['marks'].value_counts()

80.899    1
90.000    1
70.000    1
60.000    1
Name: marks, dtype: int64

In [48]:
# Find first row index label for min/max val in column
print(df['age'].idxmin())
print(df['age'].idxmax())

0
4

In [49]:
# 1. isna()-> boolean Series with True for NaN values
print(df['marks'].isna())

0    False
1    False
2     True
3    False
4    False
Name: marks, dtype: bool

In [50]:
# 2. notna() -> boolean Series with True for non-NaN values
print(df['marks'].notna())

0     True
1     True
2    False
3     True
4     True
Name: marks, dtype: bool

In [51]:
#   abs() -> absolute value of each element
print(df['marks'].abs())

0    80.899
1    90.000
2       NaN
3    70.000
4    60.000
Name: marks, dtype: float64

In [54]:
#   round() -> round each element to specified number of decimals
print(df['marks'].round(0))
print(df['marks'])

0    81.0
1    90.0
2     NaN
3    70.0
4    60.0
Name: marks, dtype: float64
0    80.899
1    90.000
2       NaN
3    70.000
4    60.000
Name: marks, dtype: float64

In [58]:
#   shift() -> shift values up/down by specified number of periods (rows)
print(df['marks'].shift(1, fill_value=0))

0     0.000
1    80.899
2    90.000
3       NaN
4    70.000
Name: marks, dtype: float64

In [59]:
# to_datetime()

# (Use age as year just for demo)

print(pd.to_datetime(df['age'], unit='D', origin='2020-01-01'))

0   2020-01-21
1   2020-01-22
2   2020-01-23
3   2020-01-21
4   2020-01-24
Name: age, dtype: datetime64[ns]

In [60]:
# fillna()
print(df['marks'].fillna(0))

0    80.899
1    90.000
2     0.000
3    70.000
4    60.000
Name: marks, dtype: float64

In [ ]:
# . cumprod() -> cumulative product of column values
print(df['marks'].cumprod())

0    8.089900e+01
1    7.280910e+03
2             NaN
3    5.096637e+05
4    3.057982e+07
Name: marks, dtype: float64

In [ ]:
# pct_change()-Percentage change between current and prior element
print(df['marks'].pct_change())

0         NaN
1    0.112498
2    0.000000
3   -0.222222
4   -0.142857
Name: marks, dtype: float64

In [ ]:
# rolling() -> rolling window calculations (e.g. sum, mean) over specified window size
print(df['marks'].rolling(window=2).sum())

0        NaN
1    170.899
2        NaN
3        NaN
4    130.000
Name: marks, dtype: float64

In [ ]:
# Append a column of row sums to a DataFrame
#here axis=1 means sum across columns for each row
df['Row Total'] = df.sum(axis=1)
print(df['Row Total'])

0    201.798
1    222.000
2     44.000
3    180.000
4    166.000
Name: Row Total, dtype: float64

In [ ]:
# Multiply every column in DataFrame by a Series
df = df.mul(s, axis=0)   # on matched rows

In [ ]:
# Selecting columns with .loc, .iloc
# simple code implementation
df = df.loc[:, 'col1':'col2']   # inclusive
df = df.iloc[:, 0:2]            # exclusive

In [68]:
# Get the integer position of a column index label
i = df.columns.get_loc('age')
print(i)

1

In [71]:
# Test if column index values are unique/monotonic
if df.columns.is_unique: pass
b = df.columns.is_monotonic_increasing
a = df.columns.is_monotonic_decreasing

In [73]:
print(b)
print(a)

False
True

In [ ]:
# Mapping a DataFrame column or Series
map = pd.Series(['red', 'green', 'blue'], index=['r', 'g', 'b'])
s = pd.Series(['r', 'g', 'r', 'b']).map(map)
# s = ['red', 'green', 'red', 'blue']

m = pd.Series([True, False], index=['Y', 'N'])
df = pd.DataFrame({'col': ['Y', 'N']})
df['col'] = df['col'].map(m)

# Note: Useful for decoding data before plotting
# Note: Sometimes referred to as a lookup function
# Note: Indexes can also be mapped if needed

In [75]:
# Find the largest and smallest values in a column
n=21
print(df['age'].nlargest(n))

print(df['age'].nsmallest(n))

4    23
2    22
1    21
0    20
3    20
Name: age, dtype: int64
0    20
3    20
1    21
2    22
4    23
Name: age, dtype: int64

In [ ]:
# Sorting the columns of a DataFrame
df = df.sort_index(axis=1, ascending=False)

#Difference between axis=0 and axis=1 in pandas:


#axis=0: This refers to the vertical axis (rows) in a DataFrame. When you perform operations with axis=0, it means you are applying the operation across rows. For example, if you use df.sum(axis=0), it will calculate the sum of each column (i.e., sum across rows).


#axis=1: This refers to the horizontal axis (columns) in a DataFrame. When you perform operations with axis=1, it means you are applying the operation across columns. For example, if you use df.sum(axis=1), it will calculate the sum of each row (i.e., sum across columns).

In [1]:
import pandas as pd

df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})

print(df)

   A  B
0  1  4
1  2  5
2  3  6

In [2]:
df.sum(axis=0)

A     6
B    15
dtype: int64

In [3]:
df.sum(axis=1)

0    5
1    7
2    9
dtype: int64

In [33]:
#Joining / combining
import pandas as pd

df1 = pd.DataFrame({
    'id': [1, 2, 3],
    'marks': [80, 90, 70]
})

df2 = pd.DataFrame({
    'id': [2, 3, 4],
    'age': [21, 22, 23]
})

In [14]:
print(pd.concat([df1, df2], axis=0, ignore_index=True))  # vertical concat

   id  marks   age
0   1   80.0   NaN
1   2   90.0   NaN
2   3   70.0   NaN
3   2    NaN  21.0
4   3    NaN  22.0
5   4    NaN  23.0

In [15]:
print(pd.concat([df1, df2], axis=1, ignore_index=True))  # horizontal concat

   0   1  2   3
0  1  80  2  21
1  2  90  3  22
2  3  70  4  23

In [18]:
# Append (same as concat)
print(df1.append(df2))

   id  marks   age
0   1   80.0   NaN
1   2   90.0   NaN
2   3   70.0   NaN
0   2    NaN  21.0
1   3    NaN  22.0
2   4    NaN  23.0

C:\Users\Nisha_Classy\AppData\Local\Temp\ipykernel_11892\620778.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df1.append(df2))

In [23]:
# Merge (like SQL JOIN)
print(pd.merge(df1, df2, on='id', how='outer')) # right join (keep all rows from df2),left join (keep all rows from df1), inner join (keep only matched rows), outer join (keep all rows from both dfs)
#inner join (keep only matched rows) , outer join (keep all rows from both dfs) are also possible

   id  marks   age
0   1   80.0   NaN
1   2   90.0  21.0
2   3   70.0  22.0
3   4    NaN  23.0

In [31]:
# Join (index-based) this is for index based joining, so we need to set the index first
# df1.set_index('id', inplace=True) #inplace=True means modify the original DataFrame, not return a new one
# df2.set_index('id', inplace=True)

print(df1.join(df2,on='id' ,how='outer'))

    marks  age
id
1      80   21
2      90   22
3      70   23

In [ ]:
# Combine First
print(df1.combine_first(df2))
#Fill missing values from other dataframe

   age  id  marks
0   21   1     80
1   22   2     90
2   23   3     70

In [35]:
# GROUPBY (Split → Apply → Combine)
# 🔹 Sample for groupby
df = pd.DataFrame({
    'dept': ['IT', 'HR', 'IT', 'HR'],
    'salary': [5000, 4000, 6000, 4500]
})

In [38]:
# 1. Basic groupby
print(df.groupby('dept').sum())

      salary
dept
HR      8500
IT     11000

In [39]:
print(df.groupby('dept').max())

      salary
dept
HR      4500
IT      6000

In [40]:
# 2. Mean
print(df.groupby('dept')['salary'].mean())

dept
HR    4250.0
IT    5500.0
Name: salary, dtype: float64

In [42]:
# 3. Multiple aggregations
print(df.groupby('dept')['salary'].agg(['sum', 'mean','max','min','count','std','var']))

        sum    mean   max   min  count         std       var
dept
HR     8500  4250.0  4500  4000      2  353.553391  125000.0
IT    11000  5500.0  6000  5000      2  707.106781  500000.0